name: Teste E2E
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: login no dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Subindo container
        run: docker compose up -d
  
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
         wait-on: 'http://localhost:80' 
         record: true
         browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Salvar Relatório Mochawesome como Artefato
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: relatorio-mochawesome
          path: tests/reports/html

      - name: Derrubando container
        if: always()
        run: docker compose down -v